import { inject, Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs';
import { SecretCardData } from '../models/game.model';

@Injectable({
  providedIn: 'root',
})
export class CardService {
  private http = inject(HttpClient);

  private knownCards: string[] = [
    // Red
    'Lightning Bolt',
    'Shock',
    'Bonecrusher Giant',
    'Goblin Guide',
    'Monastery Swiftspear',
    'Ragavan, Nimble Pilferer',
    'Dragon\'s Rage Channeler',
    'Embereth Shieldbreaker',
    'Fury',
    'Pyroblast',
    'Red Elemental Blast',
    'Skullcrack',
    'Boros Charm',
    'Rift Bolt',
    'Lava Spike',
    'Through the Breach',
    'Empty the Warrens',

    // Blue
    'Counterspell',
    'Force of Will',
    'Force of Negation',
    'Brainstorm',
    'Ponder',
    'Preordain',
    'Consider',
    'Opt',
    'Spell Pierce',
    'Mana Leak',
    'Remand',
    'Cryptic Command',
    'Snapcaster Mage',
    'Delver of Secrets',
    'Subtlety',
    'Gitaxian Probe',
    'Serum Visions',
    'Mental Misstep',
    'Dramatic Reversal',
    'Quantum Riddler',

    // Black
    'Fatal Push',
    'Thoughtseize',
    'Inquisition of Kozilek',
    'Dark Ritual',
    'Cabal Ritual',
    'Sheoldred, the Apocalypse',
    'Grief',
    'Orcish Bowmasters',
    'Griselbrand',
    'Archon of Cruelty',
    'Reanimate',
    'Entomb',
    'Unmarked Grave',
    'Vampiric Tutor',
    'Demonic Tutor',
    'Dark Confidant',
    'Whip of Erebos',
    'Duress',
    'Unholy Annex // Ritual Chamber',
    'Tragic Slip',
    'Extirpate',

    
    // Green
    'Llanowar Elves',
    'Birds of Paradise',
    'Noble Hierarch',
    'Tarmogoyf',
    'Oko, Thief of Crowns',
    'Wrenn and Six',
    'Endurance',
    'Grist, the Hunger Tide',
    'Courser of Kruphix',
    'Collected Company',
    'Chord of Calling',
    'Green Sun\'s Zenith',
    'Natural Order',
    'Craterhoof Behemoth',
    'Primeval Titan',
    'Once Upon a Time',
    'Bear Umbra',
    'Snake Umbra',
    'Ghalta, Primal Hunger',
    'Terasodon',
    'Shamanic Revelation',
    'Bloom Tender',


    // White
    'Swords to Plowshares',
    'Path to Exile',
    'Solitude',
    'Esper Sentinel',
    'Thalia, Guardian of Thraben',
    'Stoneforge Mystic',
    'Giver of Runes',
    'Mother of Runes',
    'Ranger-Captain of Eos',
    'Enlightened Tutor',
    'Teferi, Time Raveler',
    'The Wandering Emperor',
    'Elspeth, Sun\'s Champion',
    'Wrath of God',
    'Supreme Verdict',
    'Damn',
    'Silence',
    'Orim\'s Chant',
    
    // Multicolor
    'Baleful Strix',
    'Uro, Titan of Nature\'s Wrath',
    'Expressive Iteration',
    'Kolaghan\'s Command',
    'Kroxa, Titan of Death\'s Hunger',
    'Omnath, Locus of Creation',
    'Atraxa, Grand Unifier',
    'Bloodbraid Elf',
    'Ice-Fang Coatl',
    'Lightning Helix',
    'Siege Rhino',
    'Prosper, Tome-Bound',
    'Hogaak, Arisen Necropolis',
    'Jodah, the Unifier',
    // Artifacts
    'Sol Ring',
    'Mox Opal',
    'Mox Diamond',
    'Chrome Mox',
    'Sensei\'s Divining Top',
    'Mishra\'s Bauble',
    'Urza\'s Saga',
    'The One Ring',
    'Pithing Needle',
    'Chalice of the Void',
    'Aether Vial',
    'Umezawa\'s Jitte',
    'Sword of Fire and Ice',
    'Batterskull',
    'Karn, the Great Creator',
    'Hollow One',
    'Isochron Scepter',
    'Coveted Jewel',
    'Staff of Domination',
    // Lands
    'Wasteland',
    'Strip Mine',
    'Fetchlands',
    'Scalding Tarn',
    'Misty Rainforest',
    'Verdant Catacombs',
    'Marsh Flats',
    'Arid Mesa',
    'Polluted Delta',
    'Flooded Strand',
    'Bloodstained Mire',
    'Wooded Foothills',
    'Windswept Heath',
    'Shock Lands',
    'Steam Vents',
    'Breeding Pool',
    'Overgrown Tomb',
    'Temple Garden',
    'Sacred Foundry',
    'Watery Grave',
    'Stomping Ground',
    'Hallowed Fountain',
    'Blood Crypt',
    'Godless Shrine',
    'Triomes',
    'Zagoth Triome',
    'Savai Triome',
    'Ketria Triome',
    'Indatha Triome',
    'Raugrin Triome',
    'Ancient Tomb',
    'City of Traitors',
    'Karakas',
    'Gaea\'s Cradle',
    'Tolarian Academy',
    'Library of Alexandria',
    'Bazaar of Baghdad',
    'Mishra\'s Workshop',
    'Boseiju, Who Endures',
    'Three Tree City',
    // Combo Pieces
    'Thassa\'s Oracle',
    'Underworld Breach',
    'Brain Freeze',
    'Tendrils of Agony',
    'Grapeshot',
    'Show and Tell',
    'Sneak Attack',
    'Emrakul, the Aeons Torn',
    'Splinter Twin',
    'Deceiver Exarch',
    'Pestermite',
    'Kiki-Jiki, Mirror Breaker',
  ];

  getRandomCard(): Observable<SecretCardData> {
    console.log('========== CardService.getRandomCard() ==========');
    const randomIndex = Math.floor(Math.random() * this.knownCards.length);
    const cardName = this.knownCards[randomIndex];
    console.log('Random index:', randomIndex, 'out of', this.knownCards.length);
    console.log('Selected card:', cardName);

    const encodedCardName = encodeURIComponent(cardName);
    const url = `https://api.scryfall.com/cards/named?fuzzy=${encodedCardName}`;
    console.log('Scryfall API URL:', url);
    console.log('Fetching card data from Scryfall...');

    return this.http.get<SecretCardData>(url);
  }
}